services:
  auth_go:
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    ports:
      - "44000:44000"
    image: auth-go-image
    container_name: auth_go
    restart: unless-stopped
    volumes:
      - ./files:/app/files
    networks:
      - app-network
    depends_on:
      - sqlite_db

  ideas_go:
    build:
      context: .
      dockerfile: ./cmd/ideas/Dockerfile
    ports:
      - "44001:44001"
    image: main-go-image
    container_name: main_go
    restart: unless-stopped
    volumes:
      - ./files:/delivery/files
    networks:
      - app-network
    depends_on:
      - sqlite_db

  profile_go:
    build:
      context: .
      dockerfile: ./cmd/profile/Dockerfile
    ports:
      - "8003:8003"
      - "8083:8083"
    image: profile-go-image
    container_name: profile_go
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - pg_db
      - redis_service
      - main_go

  wishlists_go:
    build:
      context: .
      dockerfile: ./cmd/wish_list/Dockerfile
    ports:
      - "8007:8007"
      - "8087:8087"
    image: wishlists-go-image
    container_name: wishlists_go
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - pg_db
      - mongo_db
      - main_go

  notifications_go:
    build:
      context: .
      dockerfile: ./cmd/notifications/Dockerfile
    ports:
      - "8006:8006"
    image: notifications-go-image
    container_name: notifications_go
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - pg_db
      - redis_service
      - main_go

  promocodes_go:
    build:
      context: .
      dockerfile: ./cmd/promocodes/Dockerfile
    ports:
      - "8005:8005"
    #      - "8083:8083"
    image: promocodes-go-image
    container_name: promocodes_go
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - pg_db
      - redis_service
      - main_go
      - kafka

  sqlite_db:
    image: alpine/sqlite:3.47.1
    ports:
      - "54320:5432"
    env_file:
      - .env
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: sqlite_db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  go_back:

networks:
  app-network:
    driver: bridge
