services:
  auth_go:
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    ports:
      - "44000:44000"
    image: auth-go-image
    container_name: auth_go
    restart: unless-stopped
    volumes:
      - ./storage:/app/files
    depends_on:
      - sqlite_db

  ideas_go:
    build:
      context: .
      dockerfile: ./cmd/ideas/Dockerfile
    ports:
      - "44001:44001"
    image: ideas-go-image
    container_name: ideas_go
    restart: unless-stopped
    volumes:
      - ./storage:/app/files
      - ./images:/delivery/files
    depends_on:
      - sqlite_db

  profiles_go:
    build:
      context: .
      dockerfile: ./cmd/profiles/Dockerfile
    ports:
      - "44002:44002"
    image: profiles-go-image
    container_name: profiles_go
    restart: unless-stopped
    volumes:
      - ./storage:/app/files
    depends_on:
      - sqlite_db

  boards_go:
    build:
      context: .
      dockerfile: ./cmd/boards/Dockerfile
    ports:
      - "44003:44003"
    image: boards-go-image
    container_name: boards_go
    restart: unless-stopped
    volumes:
      - ./storage:/app/files
    depends_on:
      - sqlite_db

  comments_go:
    build:
      context: .
      dockerfile: ./cmd/comments/Dockerfile
    ports:
      - "44004:44004"
    image: comments-go-image
    container_name: comments_go
    restart: unless-stopped
    volumes:
      - ./storage:/app/files
    depends_on:
      - sqlite_db

  chats_go:
    build:
      context: .
      dockerfile: ./cmd/chats/Dockerfile
    ports:
      - "44005:44005"
    image: chats-go-image
    container_name: chats_go
    restart: unless-stopped
    volumes:
      - ./storage:/app/files
    depends_on:
      - sqlite_db

  sqlite_db:
    image: alpine/sqlite:3.47.1
    ports:
      - "54320:5432"
    env_file:
      - .env
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: sqlite_db
    restart: unless-stopped

volumes:
  go_back:
