env: "local"
auth_storage_path: "./storage/auth.db"
ideas_storage_path: "./storage/ideas.db"
boards_storage_path: "./storage/boards.db"
profiles_storage_path: "./storage/profiles.db"
token_ttl: 72h
grpc:
  auth:
    port: 44000
    timeout: 10h
  ideas:
    port: 44001
    timeout: 10s
  boards:
    port: 44002
    timeout: 10s
  profiles:
    port: 44003
    timeout: 10s
clients:
  auth:
    timeout: "4s"
    retriesCount: 5
    insecure: true
  ideas:
    timeout: "4s"
    retriesCount: 5
    insecure: true
  boards:
    timeout: "4s"
    retriesCount: 5
    insecure: true
  profiles:
    timeout: "4s"
    retriesCount: 5
    insecure: true
app_secret: "yaro-gas"
