env: "local"
auth_storage_path: "./storage/auth.db"
ideas_storage_path: "./storage/ideas.db"
token_ttl: 72h
grpc:
  auth:
    port: 44000
    timeout: 10h
  ideas:
    port: 44001
    timeout: 10s
  boards:
    port: 44002
    timeout: 10s
  profiles:
    port: 44003
    timeout: 10s
clients:
  auth:
    address: "localhost:8181"
    timeout: "4s"
    retriesCount: 5
    insecure: true
  ideas:
    address: "localhost:8182"
    timeout: "4s"
    retriesCount: 5
    insecure: true
  boards:
    address: "localhost:8183"
    timeout: "4s"
    retriesCount: 5
    insecure: true
  profiles:
    address: "localhost:8184"
    timeout: "4s"
    retriesCount: 5
    insecure: true
app_secret: "yaro21u527"
